
services:
  proxy:
    image: nginx:alpine
    container_name: parthos-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5000:5000"
    networks:
      - parthos-network
   
networks:
  parthos-network:
    external: true
