name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Rodar Docker Compose
        run: docker-compose -f docker-compose.yml up -d

      - name: Rodar Testes Parthos API
        run: docker-compose exec parthos-user-api npm test

      - name: Rodar Testes Parthos Web
        run: docker-compose exec parthos-web npm test

      - name: Fazer build de Parthos Web
        run: docker-compose exec parthos-web npm run build
